#!/bin/bash

echo "🚀 Deploying Supabase Edge Function for Background Search"
echo "=========================================="
echo ""
echo "Since we can't use the CLI directly, let's deploy via the Supabase Dashboard."
echo ""
echo "📋 STEP 1: Go to Supabase Functions"
echo "   https://supabase.com/dashboard/project/ifwscuvbtdokljwwbvex/functions"
echo ""
echo "📋 STEP 2: Click 'Create a new function'"
echo ""
echo "📋 STEP 3: Enter these details:"
echo "   • Function name: process-search"
echo "   • Method: POST"
echo ""
echo "📋 STEP 4: Copy the Edge Function code"
echo "   The code is in: supabase/functions/process-search/index.ts"
echo ""
echo "📋 STEP 5: Add Environment Variables"
echo "   Click on the function, then go to 'Settings' tab and add:"
echo ""
echo "   OPENAI_API_KEY = [Your OpenAI API key from .env.local]"
echo "   RESEND_API_KEY = [Your Resend API key from .env.local]"
echo "   ADMIN_EMAIL = [Your email from .env.local]"
echo ""
echo "📋 STEP 6: Deploy the function"
echo "   Click 'Deploy Function'"
echo ""
echo "📋 STEP 7: Create Database Webhook"
echo "   Go to: https://supabase.com/dashboard/project/ifwscuvbtdokljwwbvex/database/hooks"
echo "   • Click 'Create a new hook'"
echo "   • Name: trigger-search-processing"
echo "   • Table: search_jobs"
echo "   • Events: Insert"
echo "   • Type: HTTP Request"
echo "   • Method: POST"
echo "   • URL: https://ifwscuvbtdokljwwbvex.supabase.co/functions/v1/process-search"
echo "   • Headers:"
echo "     - Content-Type: application/json"
echo "     - Authorization: Bearer [YOUR_SERVICE_ROLE_KEY]"
echo "   • Payload: {\"jobId\": \"{id}\"}"
echo ""
echo "🎉 Once deployed, your background search will work automatically!"
echo ""
echo "Press Enter to open the Supabase Dashboard..."
read

open https://supabase.com/dashboard/project/ifwscuvbtdokljwwbvex/functions