#!/bin/bash

echo "🚀 Setting up Vercel Environment Variables"
echo "=========================================="
echo ""
echo "This script will help you add the required environment variables to Vercel."
echo ""
echo "📋 STEP 1: Go to Vercel Dashboard"
echo "   https://vercel.com/eimribar/ghostwriter-portal/settings/environment-variables"
echo ""
echo "📋 STEP 2: Add these environment variables:"
echo ""
echo "VITE_SUPABASE_URL"
echo "Value: https://ifwscuvbtdokljwwbvex.supabase.co"
echo ""
echo "VITE_SUPABASE_ANON_KEY"
echo "Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlmd3NjdXZidGRva2xqd3didmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDI0NDMsImV4cCI6MjA3MDU3ODQ0M30.QzxtYT8nbLPx9T3-PLABLXx7XtkjAg77ffUlghnQ0Xc"
echo ""
echo "VITE_OPENAI_API_KEY"
echo "Value: [Copy from your .env.local file]"
echo ""
echo "VITE_RESEND_API_KEY"
echo "Value: [Copy from your .env.local file]"
echo ""
echo "VITE_ADMIN_EMAIL"
echo "Value: eimrib@yess.ai"
echo ""
echo "VITE_GOOGLE_API_KEY"
echo "Value: AIzaSyDbuqI9sC3O4MJ483BaM4ADAvNKL7k0r1Q"
echo ""
echo "VITE_ENV"
echo "Value: production"
echo ""
echo "📋 STEP 3: Click 'Save' for each variable"
echo ""
echo "📋 STEP 4: Redeploy your application"
echo "   Go to: https://vercel.com/eimribar/ghostwriter-portal"
echo "   Click on the latest deployment"
echo "   Click '...' menu → Redeploy"
echo ""
echo "✅ Once redeployed, your background search with email will work!"
echo ""
echo "Press Enter to open Vercel Dashboard..."
read

open https://vercel.com/eimribar/ghostwriter-portal/settings/environment-variables